/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue"
  ],
  plugins: [
    require('daisyui')
  ],
  daisyui: {
    themes: [
      {
        mytheme: {
          // "primary": "#1a4d3a",
          // "primary-content": "#ffffff",
          // "secondary": "#8B4513",
          // "secondary-content": "#ffffff",
          // "accent": "#1a4d3a",
          // "accent-content": "#ffffff",
          // "neutral": "#3d4451",
          // "neutral-content": "#ffffff",
          // "base-100": "#ffffff",
          // "base-200": "#f2f2f2",
          // "base-300": "#e6e6e6",
          // "base-content": "#1f2937",
          // "info": "#3abff8",
          // "info-content": "#ffffff",
          // "success": "#36d399",
          // "success-content": "#ffffff",
          // "warning": "#fbbd23",
          // "warning-content": "#1f2937",
          // "error": "#f87272",
          // "error-content": "#ffffff",
        },
        // mytheme: {
        //   "primary": "#1a4d3a",
        //   "primary-content": "#ffffff",
        //   "secondary": "#8B4513",
        //   "accent": "#37cdbe",
        //   "neutral": "#3d4451",
        //   "base-100": "#ffffff",
        //   "info": "#3abff8",
        //   "success": "#36d399",
        //   "warning": "#fbbd23",
        //   "error": "#f87272",
        // },
        // light: {
        //   "primary": "#1a4d3a",
        //   "primary-content": "#ffffff",
        //   "secondary": "#8B4513",
        //   "accent": "#37cdbe",
        //   "neutral": "#3d4451",
        //   "base-100": "#ffffff",
        //   "info": "#3abff8",
        //   "success": "#36d399",
        //   "warning": "#fbbd23",
        //   "error": "#f87272",
        // },
        // dark: {
        //   "primary": "#2d6b4f",
        //   "primary-content": "#ffffff",
        //   "secondary": "#D2B48C",
        //   "accent": "#37cdbe",
        //   "neutral": "#3d4451",
        //   "base-100": "#2a303c",
        //   "info": "#3abff8",
        //   "success": "#36d399",
        //   "warning": "#fbbd23",
        //   "error": "#f87272",
        // },
      },
      // "light", "dark",
    ],
    // darkTheme: "dark",
    darkTheme: false,
    base: true,
    styled: true,
  },
}